### ISSUE TITLE
Again, with the improper use of `sizeof` with strings:

### ISSUE THREAD

**Issue by Pyr3z** [ghassanyounes/ghake#2]
https://github.com/ghassanyounes/ghake/blob/3b68852636765875e51d10d840d5c2543c3dc044/helpers.cpp#L386
Should be:
```cpp
std::string target(linetext.size(), '\0');
```
But I also see that you have fixed it elsewhere, so this one just wiggled past you is all :)

**Comment by ghassanyounes** [comment]
Yep, just fixed it :+1: thanks for the check
